service: serverless-user-management

plugins:
 # - serverless-finch  #plugin to create html app

custom:
  client:
    bucketName: serverless-bucket-s3-public
    indexDocument: index.html
    errorDocument: error.html

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"
        - "sqs:*"
        - "lambda:*"
        - "cloudwatch:*"
        - "apigateway:*"

resources:
  Resources:
    #USER TABLE
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: user

    #ROLE TABLE
    RolesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: roleId
            AttributeType: S
        KeySchema:
          - AttributeName: roleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: role

    #AUTHORIZATION TABLE
    AuthorizationsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: authId
            AttributeType: S
        KeySchema:
          - AttributeName: authId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: auth

    #GROUP TABLE
    GroupsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: group

    #EVENT STORE TABLE
    EventStoreDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: eventStore

      

functions:
  # ------------------------------- USER FUNCTIONS ------------------------------- #
  mediatorUser:
    handler: handler.mediatorUser
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:582373673306:userQueue #set ARN of an existing queue

  updateUser:
    handler: handler.updateUser

  createUser:
    handler: handler.createUser

  deleteUser: 
    handler: handler.deleteUser

  readUser: 
    handler: handler.readUser
    events: 
      - http: 
          path: /readUser
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "userId": "$input.params("userId")" }'

  pushEventUserToSQS: 
    handler: handler.pushEventUserToSQS 
    events: 
      - http:
          path: /pusheventusertosqs
          method: post
          cors: true
          integration: lambda

  # ------------------------------- ROLE FUNCTIONS ------------------------------- #

  mediatorRole:
    handler: handler.mediatorRole
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:582373673306:roleQueue #create new queue and set the ARN

  updateRole:
    handler: handler.updateRole

  createRole:
    handler: handler.createRole

  deleteRole: 
    handler: handler.deleteRole

  deleteAllRoles: 
    handler: handler.deleteAllRoles

  readRole: 
    handler: handler.readRole
    events: 
      - http: 
          path: /readRole
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "roleId": "$input.params("roleId")" }'
  
  getAllRoles: 
    handler: handler.getAllRoles
    events: 
      - http: 
          path: /getAllRoles
          method: get
          cors: true
          integration: lambda

  pushEventRoleToSQS: 
    handler: handler.pushEventRoleToSQS 
    events: 
      - http:
          path: /pusheventroletosqs
          method: post
          cors: true
          integration: lambda

  # ------------------------------- AUTHORIZATION FUNCTIONS ------------------------------- #

  mediatorAuth:
    handler: handler.mediatorAuth
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:582373673306:authQueue #create new queue and set the ARN

  updateAuth:
    handler: handler.updateAuth

  createAuth:
    handler: handler.createAuth

  deleteAuth: 
    handler: handler.deleteAuth

  readAuth: 
    handler: handler.readAuth
    events: 
      - http: 
          path: /readAuth
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "authId": "$input.params("authId")" }'
    
  getAllAuths: 
    handler: handler.getAllAuths
    events: 
      - http: 
          path: /getAllAuths
          method: get
          cors: true
          integration: lambda

  pushEventAuthToSQS: 
    handler: handler.pushEventAuthToSQS 
    events: 
      - http:
          path: /pusheventauthtosqs
          method: post
          cors: true
          integration: lambda

  # ------------------------------- GROUP FUNCTIONS ------------------------------- #

  mediatorGroup:
    handler: handler.mediatorGroup
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:582373673306:groupQueue #create new queue and set the ARN

  updateGroup:
    handler: handler.updateGroup

  createGroup:
    handler: handler.createGroup

  deleteGroup: 
    handler: handler.deleteGroup

  readGroup: 
    handler: handler.readGroup
    events: 
      - http: 
          path: /readGroup
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "groupId": "$input.params("groupId")" }'

  getAllGroups: 
    handler: handler.getAllGroups
    events: 
      - http: 
          path: /getAllGroups
          method: get
          cors: true
          integration: lambda

  pushEventGroupToSQS: 
    handler: handler.pushEventGroupToSQS 
    events: 
      - http:
          path: /pusheventgrouptosqs
          method: post
          cors: true
          integration: lambda

# ------------------------------- EVENT SOURCING FUNCTIONS ------------------------------- #

  mediatorRecovery: 
    handler: handler.mediatorRecovery
    events:
      - sqs:
          arn: arn:aws:sqs:eu-central-1:582373673306:eventQueue #create new queue and set the ARN

  clearDB:
    handler: handler.clearDB

  pushEventStoreToSQS: 
    handler: handler.pushEventStoreToSQS 
    timeout: 30
    events: 
      - http:
          path: /pusheventstoretosqs
          method: post
          cors: true
          integration: lambda

