service: serverless-dynamodb-streams

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

functions:
  updateUser:
    handler: handler.updateUser

  createUser:
    handler: handler.createUser

  deleteUser: 
    handler: handler.deleteUser
  
  logger:
    handler: handler.logger
    events:
      - stream: arn:aws:dynamodb:eu-central-1:582373673306:table/users/stream/2019-06-17T12:43:26.873
