service: serverless-dynamodb-streams

plugins:
  - serverless-finch

custom:
  client:
    bucketName: serverless-bucket-s3-public
    indexDocument: index.html
    errorDocument: error.html

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: users

functions:
  updateUser:
    handler: handler.updateUser

  createUser:
    handler: handler.createUser

  deleteUser: 
    handler: handler.deleteUser

  getUser: 
    handler: handler.getUser
  
  logger:
    handler: handler.logger
    events:
      - stream: arn:aws:dynamodb:eu-central-1:582373673306:table/users/stream/2019-06-17T12:43:26.873
