service: serverless-dynamodb-streams

plugins:
  - serverless-finch  #plugin to create html app

custom:
  client:
    bucketName: serverless-bucket-s3-public
    indexDocument: index.html
    errorDocument: error.html

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: users

functions:

  mediator:
    handler: handler.mediator
    #events:
     # - sqs:
        #  arn: arn:aws:sqs:eu-central-1:582373673306:eventQueue

  updateUser:
    handler: handler.updateUser

  createUser:
    handler: handler.createUser

  deleteUser: 
    handler: handler.deleteUser

  getUser: 
    handler: handler.getUser
    #events: 
    #  - http: 
      #    path: /getUser
      #    method: get
      #    cors: true

  uploadEventToSQS: 
    handler: handler.uploadEventToSQS 
    #events: 
    #  - http:
        #  path: /uploadeventtosqs
        #  method: post
        #  cors: true

